name: Build

on: [ push, pull_request, workflow_dispatch ]

env:
  BUILD_TYPE: Release

jobs:
  build-windows:
    runs-on: windows-2022
    
    defaults:
      run:
        shell: msys2 {0}
    
    steps:
    - uses: actions/checkout@v3
    
    - uses: msys2/setup-msys2@v2
      with:
        install: mingw-w64-x86_64-spdlog mingw-w64-x86_64-mesa mingw-w64-x86_64-glfw cmake make
        msystem: MINGW64
    
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_SYSTEM_NAME=Windows

    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Explorer-windows
        path: ${{github.workspace}}/build/*
        if-no-files-found: error
    
    
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install packages
      run: |
          sudo apt-get -qq update
          sudo apt-get install -y libspdlog-dev libglfw3-dev libglew-dev libgl-dev libglm-dev mesa-common-dev libgl1-mesa-dev libx11-dev
          sudo apt-get install -y libglfw3 libglew2.2

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Explorer-linux
        path: ${{github.workspace}}/build/*
        if-no-files-found: error
